name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push:
    branches:
      - "main"
jobs:
  issue_pr_lang:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: issue_pr_lang.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: kylehodgetts
          template: classic
          base: ""
          plugin_followup: yes
          plugin_languages: yes
  
  languages-used:
    name: Languages used
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          plugin_languages: yes
          plugin_languages_threshold: 2%
          plugin_languages_sections: recently-used
          token: ${{ secrets.METRICS_TOKEN }}
          user: kylehodgetts          
          base: ""
          filename: metrics.languages.svg

  lines-changed:
    name: Lines changed
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: kylehodgetts
          base: repositories
          plugin_lines: yes
